coisa = input("Escreva qualquer coisa: ")
print(f'O tipo primitivo desse valor é {type(coisa)}')
print(f'Só tem espaços? {coisa.isspace()}')
print(f'É um número? {coisa.isnumeric()}')
print(f'É alfabético? {coisa.isalpha()}')
print(f'É alfanumérico? {coisa.isalnum()}')
print(f'Está em maiúculas? {coisa.isupper()}')
print(f'Está em minúsculas? {coisa.islower()}')
print(f'Está capitalizada? {coisa.istitle}')